DATA:
  BRAIN_VOL: MICHAEL
  DATA_DIR_PATH: catena/data
  DB_COLLECTION_NAME: p667Em0476714Esb1Crop_MTLSD_predicted_affs
  DB_HOST: 10.1.0.29:27017
  DB_NAME: lsd_parallel_predictions
  DIM_2D: false
  DROP_DS_MONGOTABLE: true
  FIB: 1
  HOME: /media/samia/DATA/mounts/cephfs
  INVERT_PRED_AFFS: false
  OUTFILE: /media/samia/DATA/mounts/cephfs/catena/lsd_outputs/MTLSD/3d/clahed_hemi/model_checkpoint_latest/P667_EM04767_14_ESB_1_crop.zarr
  SAMPLE: /media/samia/DATA/mounts/cephfs/catena/data/MICHAEL/data_3d/test/P667_EM04767_14_ESB_1_crop.zarr
  SAMPLE_NAME: p667Em0476714Esb1Crop
  TRAIN_TEST_SPLIT: 1
INS_SEGMENT:
  BLOCK_SIZE:
  - 256
  - 256
  - 256
  CONTEXT:
  - 24
  - 24
  - 24
  EPSILON_AGGLOMERATE: 0.25
  FILTER_FRAGMENTS: 0.0
  FRAGMENTS_IN_XY: false
  MASK_DATASET: null
  MASK_FILE: null
  THRESHOLDS:
  - 0.5
  - 0.55
  - 0.6000000000000001
  - 0.6500000000000001
  - 0.7000000000000002
  - 0.7500000000000002
  - 0.8000000000000003
MODEL:
  CKPT_FOLDER: /media/samia/DATA/mounts/cephfs/lsd_checkpoints/MTLSD_3D/checkpoints-3dmtlsd-hemi-onlyori
  CONTROL_POINT_SPACING: &id009
  - 40
  - 40
  - 40
  CONTROL_POINT_SPACING_2D: &id010
  - 40
  - 40
  DEFECT_AUGMENT: ''
  DOWNSAMPLE_FACTORS: &id011
  - - 2
    - 2
    - 2
  - - 2
    - 2
    - 2
  - - 3
    - 3
    - 3
  DOWNSAMPLE_FACTORS_2D: &id012
  - - 2
    - 2
  - - 2
    - 2
  - - 3
    - 3
  FMAP_INC_FACTOR: 5
  GROWBOUNDARY_STEPS: 1
  GROW_INPUT: &id013
  - 0
  - 0
  - 0
  GROW_INPUT_2D: &id003
  - 36
  - 36
  INPUT_SHAPE: &id014
  - 196
  - 196
  - 196
  INPUT_SHAPE_2D: &id015
  - 196
  - 196
  INTENSITYAUG_SCALE_MAX: 1.2
  INTENSITYAUG_SCALE_MIN: 0.8
  INTENSITYAUG_SHIFT_MAX: 0.2
  INTENSITYAUG_SHIFT_MIN: -0.2
  INTENSITYSCALESHIFT_SCALE: &id016
  - 2
  - 0.5
  INTENSITYSCALESHIFT_SHIFT: &id017
  - -1
  - 0.5
  IN_CHANNELS: 1
  JITTER_SIGMA: &id018
  - &id004
    - 0
    - 2
    - 2
  - - 2
    - 2
    - 2
  JITTER_SIGMA_2D: &id019
  - - 0
    - 2
  - &id005
    - 2
    - 2
  KERNEL_SIZE_DOWN: &id020
  - - &id001
      - 3
      - 3
      - 3
    - *id001
  - - *id001
    - *id001
  - - *id001
    - *id001
  - - *id001
    - *id001
  KERNEL_SIZE_DOWN_2D: &id021
  - - &id002
      - 3
      - 3
    - *id002
  - - *id002
    - *id002
  - - *id002
    - *id002
  - - *id002
    - *id002
  KERNEL_SIZE_UP: &id022
  - - *id001
    - *id001
  - - *id001
    - *id001
  - - *id001
    - *id001
  KERNEL_SIZE_UP_2D: &id023
  - - *id002
    - *id002
  - - *id002
    - *id002
  - - *id002
    - *id002
  LOG_DIR: /media/samia/DATA/mounts/cephfs/lsd_logs/MTLSD_3D/log-3dmtlsd-hemi-onlyori
  LSD_DOWNSAMPLE: 2
  LSD_SIGMA: 80
  MAX_MISALIGN: &id024
  - 0
  - 1
  NUM_FMAPS: 12
  NUM_FMAPS_OUT: 12
  OUTPUT_DIR: /media/samia/DATA/mounts/cephfs/lsd_snapshots/MTLSD_3D/snapshots_3dmtlsd-hemi-onlyori
  OUTPUT_SHAPE: &id025
  - 72
  - 72
  - 72
  OUTPUT_SHAPE_2D: &id026
  - 72
  - 72
  PAD_CONV: valid
  PROB_SHIFT: &id027
  - 0
  - 0.1
  PROB_SLIP: &id028
  - 0
  - 0.1
  ROTATION_INTERVAL: &id029
  - 0
  - 1.5707963267948966
  SUBSAMPLE: 8
  TRANSPOSE: &id030
  - 0
  - 1
  - 2
  TRANSPOSE_2D: &id031
  - 0
  - 1
  VOXEL_SIZE: &id032
  - 8
  - 8
  - 8
  VOXEL_SIZE_2D: &id033
  - 12
  - 12
MODEL_ANISO:
  CKPT_FOLDER: /media/samia/DATA/mounts/cephfs/lsd_checkpoints/MTLSD_3D/checkpoints_3dmtlsd-cremi-cropped-z30-170
  CONTROL_POINT_SPACING:
  - 4
  - 4
  - 10
  CONTROL_POINT_SPACING_2D: &id008
  - 4
  - 4
  DEFECT_AUGMENT: ''
  DOWNSAMPLE_FACTORS:
  - - 1
    - 2
    - 2
  - - 2
    - 2
    - 2
  - - 3
    - 3
    - 3
  DOWNSAMPLE_FACTORS_2D:
  - - 1
    - 2
  - - 2
    - 2
  - - 3
    - 3
  FMAP_INC_FACTOR: 5
  GROWBOUNDARY_STEPS: 1
  GROW_INPUT:
  - 36
  - 36
  - 36
  GROW_INPUT_2D: *id003
  INPUT_SHAPE:
  - 132
  - 268
  - 268
  INPUT_SHAPE_2D:
  - 268
  - 268
  INTENSITYAUG_SCALE_MAX: 1.2
  INTENSITYAUG_SCALE_MIN: 0.8
  INTENSITYAUG_SHIFT_MAX: 0.2
  INTENSITYAUG_SHIFT_MIN: -0.2
  INTENSITYSCALESHIFT_SCALE:
  - 2
  - 0.5
  INTENSITYSCALESHIFT_SHIFT:
  - -1
  - 0.5
  IN_CHANNELS: 1
  JITTER_SIGMA: *id004
  JITTER_SIGMA_2D: *id005
  KERNEL_SIZE_DOWN:
  - - &id006
      - 1
      - 3
      - 3
    - *id006
  - - *id001
    - *id001
  - - *id001
    - *id001
  - - *id001
    - *id001
  KERNEL_SIZE_DOWN_2D:
  - - &id007
      - 1
      - 3
    - *id007
  - - *id002
    - *id002
  - - *id002
    - *id002
  - - *id002
    - *id002
  KERNEL_SIZE_UP:
  - - *id002
    - *id002
  - - *id002
    - *id002
  - - *id002
    - *id002
  LOG_DIR: /media/samia/DATA/mounts/cephfs/lsd_logs/MTLSD_3D/log-3dmtlsd-cremi-cropped-z30-170
  LSD_DOWNSAMPLE: 2
  LSD_SIGMA: 80
  MAX_MISALIGN: 10
  NUM_FMAPS: 12
  NUM_FMAPS_OUT: 12
  OUTPUT_DIR: /media/samia/DATA/mounts/cephfs/lsd_snapshots/MTLSD_3D/snapshots_3dmtlsd-cremi-cropped-z30-170
  OUTPUT_SHAPE:
  - 72
  - 144
  - 144
  OUTPUT_SHAPE_2D:
  - 144
  - 144
  PAD_CONV: valid
  PROB_SHIFT: 0.5
  PROB_SLIP: 0.5
  ROTATION_INTERVAL:
  - 0
  - 1.5707963267948966
  SUBSAMPLE: 8
  TRANSPOSE:
  - 1
  - 2
  TRANSPOSE_2D:
  - 0
  - 1
  VOXEL_SIZE:
  - 40
  - 4
  - 4
  VOXEL_SIZE_2D: *id008
MODEL_ISO:
  CKPT_FOLDER: /media/samia/DATA/mounts/cephfs/lsd_checkpoints/MTLSD_3D/checkpoints-3dmtlsd-hemi-onlyori
  CONTROL_POINT_SPACING: *id009
  CONTROL_POINT_SPACING_2D: *id010
  DEFECT_AUGMENT: ''
  DOWNSAMPLE_FACTORS: *id011
  DOWNSAMPLE_FACTORS_2D: *id012
  FMAP_INC_FACTOR: 5
  GROWBOUNDARY_STEPS: 1
  GROW_INPUT: *id013
  GROW_INPUT_2D: *id003
  INPUT_SHAPE: *id014
  INPUT_SHAPE_2D: *id015
  INTENSITYAUG_SCALE_MAX: 1.2
  INTENSITYAUG_SCALE_MIN: 0.8
  INTENSITYAUG_SHIFT_MAX: 0.2
  INTENSITYAUG_SHIFT_MIN: -0.2
  INTENSITYSCALESHIFT_SCALE: *id016
  INTENSITYSCALESHIFT_SHIFT: *id017
  IN_CHANNELS: 1
  JITTER_SIGMA: *id018
  JITTER_SIGMA_2D: *id019
  KERNEL_SIZE_DOWN: *id020
  KERNEL_SIZE_DOWN_2D: *id021
  KERNEL_SIZE_UP: *id022
  KERNEL_SIZE_UP_2D: *id023
  LOG_DIR: /media/samia/DATA/mounts/cephfs/lsd_logs/MTLSD_3D/log-3dmtlsd-hemi-onlyori
  LSD_DOWNSAMPLE: 2
  LSD_SIGMA: 80
  MAX_MISALIGN: *id024
  NUM_FMAPS: 12
  NUM_FMAPS_OUT: 12
  OUTPUT_DIR: /media/samia/DATA/mounts/cephfs/lsd_snapshots/MTLSD_3D/snapshots_3dmtlsd-hemi-onlyori
  OUTPUT_SHAPE: *id025
  OUTPUT_SHAPE_2D: *id026
  PAD_CONV: valid
  PROB_SHIFT: *id027
  PROB_SLIP: *id028
  ROTATION_INTERVAL: *id029
  SUBSAMPLE: 8
  TRANSPOSE: *id030
  TRANSPOSE_2D: *id031
  VOXEL_SIZE: *id032
  VOXEL_SIZE_2D: *id033
PREPROCESS:
  HISTOGRAM_MATCH:
  - HEMI
  - POPEYE
SYSTEM:
  CACHE_SIZE: 40
  NUM_GPUS: 1
  NUM_WORKERS: 3
  VERBOSE: true
TRAIN:
  BATCH_SIZE: 4
  CHECKPOINT: /media/samia/DATA/mounts/cephfs/lsd_checkpoints/MTLSD_3D/HEMI/clahed_hemi/model_checkpoint_latest
  DEVICE: cuda:0
  EPOCHS: 400000
  INITIAL_LR: 5.0e-05
  LR_BETAS:
  - 0.95
  - 0.999
  LR_NEIGHBORHOOD:
  - - -1
    - 0
    - 0
  - - 0
    - -1
    - 0
  - - 0
    - 0
    - -1
  - - -3
    - 0
    - 0
  - - 0
    - -3
    - 0
  - - 0
    - 0
    - -3
  - - -9
    - 0
    - 0
  - - 0
    - -9
    - 0
  - - 0
    - 0
    - -9
  MODEL_TYPE: MTLSD
  NEIGHBORHOOD:
  - - -1
    - 0
    - 0
  - - 0
    - -1
    - 0
  - - 0
    - 0
    - -1
  NEIGHBORHOOD_2D:
  - - 0
    - -1
  - - -1
    - 0
  SAVE_EVERY: 2000
