name: napari-env
channels:
  - http://conda.anaconda.org/gurobi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.0
  - libsqlite=3.43.2
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.3
  - pip=23.2.1
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
      - addict==2.4.0
      - alabaster==0.7.13
      - app-model==0.2.2
      - appdirs==1.4.4
      - asciitree==0.3.3
      - asttokens==2.4.0
      - atomicwrites==1.4.1
      - attrs==23.1.0
      - babel==2.13.0
      - backcall==0.2.0
      - blinker==1.7.0
      - boto3==1.34.65
      - botocore==1.34.65
      - brotli==1.1.0
      - build==1.0.3
      - cachetools==5.3.2
      - cachey==0.2.1
      - certifi==2023.7.22
      - chardet==5.2.0
      - charset-normalizer==3.3.0
      - click==8.1.7
      - cloud-files==4.24.0
      - cloud-volume==8.32.0
      - cloudpickle==2.2.1
      - comm==0.1.4
      - compressed-segmentation==2.2.2
      - compresso==3.3.0
      - configargparse==1.7
      - connected-components-3d==3.12.4
      - contourpy==1.1.1
      - crackle-codec==0.9.0
      - crc32c==2.4
      - cycler==0.12.1
      - dash==2.16.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2023.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - deflate==0.5.0
      - dijkstra3d==1.14.0
      - dill==0.3.8
      - distributed==2023.12.1
      - docstring-parser==0.15
      - docutils==0.17.1
      - dracopy==1.4.0
      - edt==2.4.0
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fastremap==1.14.1
      - fill-voids==2.0.6
      - flask==3.0.2
      - flybrains==0.2.9
      - fonttools==4.43.1
      - fpzip==1.2.3
      - freetype-py==2.4.0
      - fsspec==2023.9.2
      - fuzzywuzzy==0.18.0
      - gevent==24.2.1
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-api-core==2.17.1
      - google-apitools==0.5.32
      - google-auth==2.28.2
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.16.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.0
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - h5py==3.10.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - httplib2==0.22.0
      - idna==3.4
      - igraph==0.11.4
      - imagecodecs==2023.9.18
      - imageio==2.31.5
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - in-n-out==0.1.9
      - inflection==0.5.1
      - iniconfig==2.0.0
      - ipykernel==6.25.2
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.2
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.24
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.1
      - jupyter-core==5.4.0
      - jupyterlab-widgets==3.0.10
      - kimimaro==3.5.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - locket==1.0.0
      - magicgui==0.7.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - matplotlib-scalebar==0.8.1
      - mdurl==0.1.2
      - microfilm==0.2.1
      - molesq==0.4.0
      - morphops==0.1.13
      - msgpack==1.0.7
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - napari==0.4.18
      - napari-console==0.0.9
      - napari-labels-overlap==0.0.3
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.0a2
      - napari-svg==0.1.10
      - napari-tools-menu==0.1.19
      - natsort==8.4.0
      - navis==1.5.0
      - nbformat==5.10.3
      - ncollpyde==0.19.0
      - nest-asyncio==1.5.8
      - networkx==3.1
      - neuroglancer==2.37
      - npe2==0.7.2
      - nptyping==2.5.0
      - numcodecs==0.12.0
      - numpy==1.26.0
      - numpydoc==1.5.0
      - oauth2client==4.1.3
      - open3d==0.18.0
      - orjson==3.9.15
      - packaging==23.2
      - pandas==2.1.1
      - parso==0.8.3
      - partd==1.4.1
      - pathos==0.3.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - pint==0.22
      - platformdirs==3.11.0
      - plotly==5.20.0
      - pluggy==1.4.0
      - pooch==1.7.0
      - posix-ipc==1.1.1
      - pox==0.3.4
      - ppft==1.7.6.8
      - prompt-toolkit==3.0.39
      - protobuf==4.25.3
      - psutil==5.9.5
      - psygnal==0.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pydantic==1.10.13
      - pyfqmr==0.2.0
      - pygments==2.16.1
      - pykdtree==1.3.11
      - pynrrd==1.0.0
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pypng==0.20220715.0
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - pyquaternion==0.9.9
      - pyside6==6.6.2
      - pyside6-addons==6.6.2
      - pyside6-essentials==6.6.2
      - pysimdjson==6.0.2
      - pyspng-seunglab==1.1.1
      - pytest==8.1.1
      - python-dateutil==2.8.2
      - python-jsonschema-objects==0.5.4
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - rdata==0.11.2
      - referencing==0.30.2
      - requests==2.31.0
      - retrying==1.3.4
      - rich==13.6.0
      - rpds-py==0.10.4
      - rsa==4.9
      - s3transfer==0.10.1
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - scipy==1.11.3
      - seaborn==0.13.2
      - shapely==2.0.3
      - shiboken6==6.6.2
      - simplejpeg==1.7.2
      - six==1.16.0
      - skeletor==1.2.3
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.3
      - superqt==0.6.1
      - tblib==3.0.0
      - tenacity==8.2.3
      - texttable==1.7.0
      - threadpoolctl==3.4.0
      - tifffile==2023.9.26
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.11.2
      - trimesh==4.2.0
      - typer==0.9.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==1.26.18
      - vispy==0.12.2
      - wcwidth==0.2.8
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.10
      - wrapt==1.15.0
      - xarray==2023.10.1
      - xs3d==1.6.0
      - xxhash==3.4.1
      - zarr==2.16.1
      - zfpc==0.1.2
      - zfpy==1.0.0
      - zict==3.0.0
      - zipp==3.17.0
      - zope-event==5.0
      - zope-interface==6.2
      - zstandard==0.22.0
