name: napari-env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - ncurses=6.4
  - openssl=3.1.3
  - pip=23.2.1
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
      - alabaster==0.7.13
      - app-model==0.2.2
      - appdirs==1.4.4
      - asciitree==0.3.3
      - asttokens==2.4.0
      - atomicwrites==1.4.1
      - attrs==23.1.0
      - babel==2.13.0
      - backcall==0.2.0
      - build==1.0.3
      - cachetools==5.3.2
      - cachey==0.2.1
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - comm==0.1.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - dask==2023.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - distributed==2023.12.1
      - docstring-parser==0.15
      - docutils==0.17.1
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - fasteners==0.19
      - fonttools==4.43.1
      - freetype-py==2.4.0
      - fsspec==2023.9.2
      - google-apitools==0.5.32
      - google-auth==2.23.4
      - h5py==3.10.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - httplib2==0.22.0
      - idna==3.4
      - imagecodecs==2023.9.18
      - imageio==2.31.5
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - in-n-out==0.1.9
      - ipykernel==6.25.2
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.1
      - jupyter-core==5.4.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - locket==1.0.0
      - magicgui==0.7.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - matplotlib-scalebar==0.8.1
      - mdurl==0.1.2
      - microfilm==0.2.1
      - msgpack==1.0.7
      - mypy-extensions==1.0.0
      - napari==0.4.18
      - napari-console==0.0.9
      - napari-labels-overlap==0.0.3
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.0a2
      - napari-svg==0.1.10
      - napari-tools-menu==0.1.19
      - natsort==8.4.0
      - nest-asyncio==1.5.8
      - networkx==3.1
      - neuroglancer==2.37
      - npe2==0.7.2
      - numcodecs==0.12.0
      - numpy==1.26.0
      - numpydoc==1.5.0
      - oauth2client==4.1.3
      - packaging==23.2
      - pandas==2.1.1
      - parso==0.8.3
      - partd==1.4.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - pint==0.22
      - platformdirs==3.11.0
      - pooch==1.7.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - psygnal==0.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.13
      - pygments==2.16.1
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - referencing==0.30.2
      - requests==2.31.0
      - rich==13.6.0
      - rpds-py==0.10.4
      - rsa==4.9
      - scikit-image==0.22.0
      - scipy==1.11.3
      - six==1.16.0
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.3
      - superqt==0.6.1
      - tblib==3.0.0
      - tifffile==2023.9.26
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.11.2
      - typer==0.9.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.0.6
      - vispy==0.12.2
      - wcwidth==0.2.8
      - wrapt==1.15.0
      - xarray==2023.10.1
      - zarr==2.16.1
      - zict==3.0.0
      - zipp==3.17.0
