name: nglance
channels:
  - conda-forge
  - defaults
dependencies:
  - archspec=0.2.3
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - distro=1.9.0
  - fmt=10.2.1
  - icu=73.2
  - idna=3.7
  - jsonpatch=1.33
  - krb5=1.21.2
  - libarchive=3.7.2
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libiconv=1.17
  - libmamba=1.5.8
  - libnghttp2=1.58.0
  - libsolv=0.7.29
  - libssh2=1.11.0
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - ncurses=6.4
  - openssl=3.3.0
  - packaging=24.0
  - platformdirs=4.2.1
  - pluggy=1.5.0
  - pybind11-abi=4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.66.2
  - truststore=0.8.0
  - urllib3=2.2.1
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - anyio==4.3.0
    - appnope==0.1.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asciitree==0.3.3
    - asttokens==2.4.1
    - async-lru==2.0.4
    - atomicwrites==1.4.1
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blosc2==2.6.2
    - brotli==1.1.0
    - cachetools==5.3.3
    - caveclient==5.21.0
    - cffi==1.16.0
    - click==8.1.7
    - cloudpickle==3.0.0
    - comm==0.2.2
    - conda==24.3.0
    - daisy==1.1
    - dask==2024.4.2
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dnspython==2.6.1
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - fasteners==0.19
    - fastjsonschema==2.19.1
    - fqdn==1.5.1
    - fsspec==2024.3.1
    - funlib-geometry==0.3.0
    - funlib-math==0.1
    - funlib-persistence==0.4.0
    - google-apitools==0.5.32
    - google-auth==2.29.0
    - h11==0.14.0
    - h5py==3.11.0
    - httpcore==1.0.5
    - httplib2==0.22.0
    - httpx==0.27.0
    - importlib-metadata==7.1.0
    - ipykernel==6.29.4
    - ipython==8.23.0
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - json5==0.9.25
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.8
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.1
    - libmambapy==1.5.8
    - locket==1.0.0
    - mamba==1.5.8
    - markupsafe==2.1.5
    - matplotlib-inline==0.1.7
    - menuinst==2.0.2
    - mistune==3.0.2
    - msgpack==1.0.8
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.10.4
    - ndindex==1.8
    - nest-asyncio==1.6.0
    - networkx==3.3
    - neuroglancer==2.37
    - nglui==3.0.2
    - notebook-shim==0.2.4
    - numcodecs==0.12.1
    - numexpr==2.10.0
    - numpy==1.26.4
    - oauth2client==4.1.3
    - overrides==7.7.0
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - partd==1.4.1
    - pexpect==4.9.0
    - pillow==10.3.0
    - pip==23.3.1
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - psutil==5.9.8
    - psycopg2-binary==2.9.9
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pyarrow==16.0.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycosat==0.6.6
    - pygments==2.17.2
    - pymongo==4.7.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==26.0.2
    - referencing==0.35.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.18.0
    - rsa==4.9
    - ruamel-yaml==0.18.6
    - ruamel-yaml-clib==0.2.8
    - send2trash==1.8.3
    - setuptools==68.2.2
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - tables==3.9.2
    - terminado==0.18.1
    - tinycss2==1.3.0
    - tomli==2.0.1
    - toolz==0.12.1
    - tornado==6.4
    - traitlets==5.14.3
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.11.0
    - tzdata==2024.1
    - uri-template==1.3.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - wheel==0.41.2
    - zarr==2.17.2
    - zipp==3.18.1
    - zstandard==0.22.0
