import numpy as np
import pandas as pd
import zarr
import os
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from skimage.measure import marching_cubes
import seaborn as sns

# --- CONFIGURATION ---
# Path to the CSV generated by the previous script
CSV_PATH = "/media/samia/DATA/mounts/fibserver1/smohinta_data/graid_backup/blackwell_backup/PHD/codebases/catena/mitochondria_segmentation/analysis/cumulative_mito_analysis.csv"
# Directory containing your Zarrs
ZARR_ROOT = "/media/samia/DATA/mounts/gpu2/mito-seg/catena_data/HEMI-OCTO-CORRECT/data_3d/train"

# Resolution (needed for correct aspect ratio in 3D)
VOXEL_RES = (8, 8, 8)  # z, y, x

# Keys in Zarr
LABEL_KEY = 'volumes/labels/neuron_ids'


def load_zarr_volume(path, key):
    try:
        f = zarr.open(path, mode='r')
        return f[key][:]
    except Exception as e:
        print(f"Error loading {path}: {e}")
        return None


def get_mesh_from_label(label_vol, label_id):
    """
    Extracts a 3D mesh for a specific label ID using Marching Cubes.
    Returns vertices and faces centered at (0,0,0).
    """
    # 1. Create a local binary mask (Crop to bbox to save memory)
    # Find coordinates
    coords = np.argwhere(label_vol == label_id)
    if coords.size == 0: return None, None, None

    min_z, min_y, min_x = coords.min(axis=0)
    max_z, max_y, max_x = coords.max(axis=0) + 1

    # Pad by 1 pixel to ensure mesh closes
    crop = label_vol[min_z:max_z, min_y:max_y, min_x:max_x] == label_id
    crop = np.pad(crop, 1, mode='constant')

    # 2. Marching Cubes
    try:
        verts, faces, normals, values = marching_cubes(crop, level=0.5, step_size=1)

        # 3. Apply Voxel Resolution (Anisotropy)
        verts = verts * np.array(VOXEL_RES)

        # 4. Center the mesh
        centroid = verts.mean(axis=0)
        verts -= centroid

        # Calculate real bounding box center in the original volume for Neuroglancer
        global_center = (np.array([min_z, min_y, min_x]) * np.array(VOXEL_RES)) + centroid

        return verts, faces, global_center
    except Exception as e:
        print(f"  Mesh generation failed for ID {label_id}: {e}")
        return None, None, None


def plot_3d_gallery(candidates_dict, save_name="mito_gallery_panel_c.pdf"):
    """
    Plots a grid of 3D meshes.
    candidates_dict: { 'Category Name': [ (label_id, sample_name, verts, faces), ... ] }
    """
    categories = list(candidates_dict.keys())
    n_rows = len(categories)
    n_cols = max([len(v) for v in candidates_dict.values()])

    fig = plt.figure(figsize=(n_cols * 3, n_rows * 3))

    # Colors for categories (mimicking the reference image)
    colors = {
        'Globular': '#9b59b6',  # Purple
        'Filamentous': '#e67e22',  # Orange
        'Complex': '#2ecc71',  # Green
        'Crowded': '#e74c3c'  # Red
    }

    print("\n--- Rendering 3D Gallery ---")

    for row, (category, items) in enumerate(candidates_dict.items()):
        color = colors.get(category.split(' ')[0], 'gray')

        for col, item in enumerate(items):
            if item is None: continue

            label_id, sample, verts, faces, metric_val = item

            # Setup subplot
            ax = fig.add_subplot(n_rows, n_cols, (row * n_cols) + col + 1, projection='3d')

            # Create Mesh Collection
            mesh = Poly3DCollection(verts[faces], alpha=0.9)
            mesh.set_facecolor(color)
            mesh.set_edgecolor('k')
            mesh.set_linewidth(0.05)  # Very thin lines for detail

            ax.add_collection3d(mesh)

            # Auto-scale axis
            scale = np.concatenate(verts).flatten()
            ax.auto_scale_xyz(scale, scale, scale)

            # Clean up axes
            ax.set_axis_off()
            ax.view_init(elev=30, azim=45)  # Standard isometric-ish view

            # Titles
            if col == 0:
                ax.text2D(-0.2, 0.5, category, transform=ax.transAxes,
                          fontsize=16, fontweight='bold', rotation=90, va='center')

            # Individual Label Info
            title_txt = f"ID: {label_id}\nVal: {metric_val:.2f}"
            ax.set_title(title_txt, fontsize=10)

    plt.tight_layout()
    plt.savefig(save_name, dpi=300)
    print(f"Gallery saved to {save_name}")
    plt.close()


def main():
    # 1. Load Data
    if not os.path.exists(CSV_PATH):
        print("CSV file not found. Run the analysis script first.")
        return

    df = pd.read_csv(CSV_PATH)

    # Filter valid
    df = df.dropna(subset=['DCI', 'EFI'])

    # 2. Select Candidates based on Metrics
    # We pick the "Top 5" for each interesting category to form rows

    # A. Filamentous (Top Elongation)
    top_elong = df.nlargest(5, 'Elongation')

    # B. Complex/Fragile (Top EFI)
    top_efi = df.nlargest(5, 'EFI')

    # C. Crowded (Top DCI)
    top_dci = df.nlargest(5, 'DCI')

    # D. Globular (Bottom Elongation, but decent volume to avoid noise)
    # Filter for volume > median to avoid specks
    vol_median = df['Volume_um3'].median()
    globular = df[df['Volume_um3'] > vol_median].nsmallest(5, 'Elongation')

    selection = {
        'Filamentous (Elongation)': (top_elong, 'Elongation'),
        'Complex (EFI)': (top_efi, 'EFI'),
        'Crowded (DCI)': (top_dci, 'DCI'),
        'Globular (Round)': (globular, 'Elongation')
    }

    gallery_data = {}
    ng_coordinates = []

    # 3. Extract Meshes
    for category_name, (sub_df, metric_col) in selection.items():
        gallery_data[category_name] = []
        print(f"\nProcessing Category: {category_name}")

        for _, row in sub_df.iterrows():
            sample = row['Sample']
            label_id = int(row['Label_ID'])
            metric_val = row[metric_col]

            # Construct Zarr path
            # Assuming folder structure is Flat or contained in ZARR_ROOT
            # We try to find the folder that matches the sample name

            # Crude search for the zarr folder
            found_path = None
            for root, dirs, files in os.walk(ZARR_ROOT):
                for d in dirs:
                    if sample in d and d.endswith('.zarr'):
                        found_path = os.path.join(root, d)
                        break

            if not found_path:
                print(f"  Could not find Zarr for sample: {sample}")
                continue

            # Load Volume
            labels = load_zarr_volume(found_path, LABEL_KEY)
            if labels is None: continue

            # Get Mesh
            verts, faces, center_coord = get_mesh_from_label(labels, label_id)

            if verts is not None:
                gallery_data[category_name].append((label_id, sample, verts, faces, metric_val))

                # Store coordinates for Neuroglancer text output
                # center_coord is in nm (z, y, x). Neuroglancer usually wants voxels or nm depending on setup.
                # Here we store nm.
                ng_coordinates.append({
                    'Category': category_name,
                    'Sample': sample,
                    'ID': label_id,
                    'Position_nm': center_coord.astype(int).tolist()
                })
                print(f"  Extracted ID {label_id} (Metric: {metric_val:.2f})")

    # 4. Generate Static Plot
    plot_3d_gallery(gallery_data)

    # 5. Print Neuroglancer "Cheat Sheet"
    print("\n" + "=" * 50)
    print("NEUROGLANCER COORDINATES (Paste these into your viewer)")
    print("=" * 50)
    for item in ng_coordinates:
        # Convert nm to voxel coordinates for display if needed, 
        # but here we print the raw info.
        pos = item['Position_nm']
        print(f"[{item['Category']}] Sample: {item['Sample']} | ID: {item['ID']}")
        print(f"   Position (nm): {pos}  <-- Move view here")
        print("-" * 20)


if __name__ == "__main__":
    main()
